version: "3.8"
services:

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api-build
    container_name: LibreChat-API
    ports:
      - "3080:3080"
    depends_on:
      - mongodb
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./images:/app/client/public/images
      - ./librechat.yaml:/app/librechat.yaml

  client:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod-stage
    container_name: LibreChat-NGINX
    ports:
      - "8000:80"
    depends_on:
      - api
    restart: always
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf

  mongodb:
    container_name: chat-mongodb
    ports:
      - "27018:27017"
    image: jfrog.apa-techs.com/docker/mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth


  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.0
    ports:
       - "7700:7700"
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data:/meili_data
