# Build API, Client and Data Provider
FROM node:20-alpine AS base

# Build data-provider
FROM base AS data-provider-build
WORKDIR /app/packages/data-provider
COPY ./packages/data-provider ./
RUN npm install
RUN touch .env
RUN npm config set fetch-retry-maxtimeout 300000
RUN apk add --no-cache g++ make python3 py3-pip
RUN npm install -g node-gyp
RUN apk --no-cache add curl && \
    npm install
RUN npm run build


# Node API setup
FROM data-provider-build AS api-build
WORKDIR /app/api
COPY api/package*.json ./
COPY api/ ./
# Copy data-provider to API's node_modules
RUN mkdir -p /app/api/node_modules/librechat-data-provider/
RUN cp -R /app/packages/data-provider/* /app/api/node_modules/librechat-data-provider/
RUN npm install
COPY --from=client-build /app/client/dist /app/client/dist
EXPOSE 3080
ENV HOST=0.0.0.0
CMD ["node", "server/index.js"]