# Build API, Client and Data Provider
FROM node:20-alpine AS base

# Build data-provider
FROM base AS data-provider-build
WORKDIR /app/packages/data-provider
COPY ./packages/data-provider ./
RUN npm install
RUN touch .env
RUN npm config set fetch-retry-maxtimeout 300000
RUN apk add --no-cache g++ make python3 py3-pip
RUN npm install -g node-gyp
RUN apk --no-cache add curl && \
    npm install
RUN npm run build

# React client build
FROM data-provider-build AS client-build
WORKDIR /app/client
COPY ./client/ ./
# Copy data-provider to client's node_modules
RUN mkdir -p /app/client/node_modules/librechat-data-provider/
RUN cp -R /app/packages/data-provider/* /app/client/node_modules/librechat-data-provider/
RUN npm install
ENV NODE_OPTIONS="--max-old-space-size=2048"
RUN npm run build

# Nginx setup
FROM nginx:1.21.1-alpine AS prod-stage
COPY ./client/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
